### ISSUE TITLE
Missing Meta

### ISSUE THREAD

**Issue by yu-luckyvr** [taptap/TapPayment-Unity#1]
When using developing custom packages,  meta files must be included.

If end user download package through package manager, the folder is immutable, meaning that end user will not be able to add meta themself( they could copy the whole folder out to Assets\, but it defeat the purpose of using package).

Even if they folk directly using git, missing meta will have those asset creating different meta on each machine.

1. Asset Packages/com.taptap.tds.payment/Editor has no meta file
2. Asset Packages/com.taptap.tds.payment/CHANGELOG.md has no meta file
3. Asset Packages/com.taptap.tds.payment/Editor/TapTap.Payment.Editor.asmdef
4. Asset Packages/com.taptap.tds.payment/package.json has no meta file
5. Asset Packages/com.taptap.tds.payment/Plugins/Android/libs/TapPayment_3.9.0.aar  
6. Asset Packages/com.taptap.tds.payment/README.md has no meta file

**Comment by hexinghuaxd** [comment]
It has been fixed in the latest version 3.11.0.
